### ISSUE TITLE
Item transformers are very tempermental...(works on and off)

### ISSUE THREAD

**Issue by ALongPantsMan** [ImagicTheCat/vRP#192] opened 2017-06-09 00:41 UTC
Anyone have an issue with placing multiple transformers? I had the weedfield, trevor's house(to buy weed), meth lab(make) and buys around sandy(All worked for a few hours). HOWEVER, I added a jail location at the prison and started adding markers and blips and now I am not able to have more than 2 transformers at a time? It seems to be that the weedfield stays indefinitely, but it will switch between Trevor and the Meth lab depending on which code block is placed first in the file.... any ideas...? Doubt that it has anything to do with the markers and blips, but that is what I was messing with when I restarted and the transformers had broken... :confused:

`cfg.item_transformers = {
  -- example of harvest item transformer
  {
    name="Bill and Dave's Farm", -- menu name
    -- permission = "harvest.water_bottle", -- you can add a permission
    r=0,g=125,b=255, -- color
    max_units=10,
    units_per_minute=5,
    x=2224.05029296875,y=5577.7861328125,53,z=53.7328758239746, -- pos
    radius=5, height=1.5, -- area
    action="Harvest", -- action name
    description="Wanna help trim some buds? We'll toss ya some green both ways ;) Take it back to Trevor in Sandy Shores for some more cash!", -- action description
    in_money=0, -- money taken per unit
    out_money=50, -- money earned per unit
    reagents={}, -- items taken per unit
    products={ -- items given per unit
      ["weed"] = 1
    }
  }
}

-- define transformers randomly placed on the map
cfg.hidden_transformers = {
  ["weed field"] = {
    def = {
      name="Bill and Dave's Farm", -- menu name
      -- permission = "harvest.water_bottle", -- you can add a permission
      r=0,g=200,b=0, -- color
      max_units=30,
      units_per_minute=1,
      x=0,y=0,z=0, -- pos
      radius=5, height=1.5, -- area
      action="Harvest", -- action name
      description="Wanna help trim some buds? We'll toss ya some green both ways ;) Take it back to Trevor in Sandy Shores for some more cash!", -- action description
      in_money=0, -- money taken per unit
      out_money=50, -- money earned per unit
      reagents={}, -- items taken per unit
      products={ -- items given per unit
        ["weed"] = 1
      }
    },
    positions = {
      {1873.36901855469,3658.46215820313,33.8029747009277},
      {1856.33776855469,3635.12109375,34.1897926330566},
      {1830.75390625,3621.44140625,33.8487205505371}
    }
  }
}

-- time in minutes before hidden transformers are relocated (min is 5 minutes)
cfg.hidden_transformer_duration = 5*24*60 -- 5 days

-- configure the information reseller (can sell hidden transformers positions)
cfg.informer = {
  infos = {
    ["weed field"] = 3000
  },
  positions = {
    {1821.12390136719,3685.9736328125,34.2769317626953},
    {1804.2958984375,3684.12280273438,34.217945098877}
  },
  interval = 2, -- interval in minutes for the reseller respawn
  duration = 100, -- duration in minutes of the spawned reseller
  blipid = 133,
  blipcolor = 2
}

cfg.item_transformers = {
  -- example of harvest item transformer
  {
    name="Trevor", -- menu name
    -- permission = "harvest.water_bottle", -- you can add a permission
    r=0,g=125,b=255, -- color
    max_units=50,
    units_per_minute=5,
    x=1972.6060,y=3817.0440,z=33.4363, -- pos
    radius=5, height=1.5, -- area
    action="Sell Trevor weed.", -- action name
    description="WOOO-WEEE that smells like some dankity dank! Here, take the money and get the hell of my porch before someone sees you!", -- action description
    in_money=0, -- money taken per unit
    out_money=250, -- money earned per unit
    reagents={
	  ["weed"] = 1}, -- items taken per unit
    products={ -- items given per unit
    }
  }
}

cfg.item_transformers = {
  -- example of harvest item transformer
  {
    name="Meth Lab", -- menu name
    -- permission = "harvest.water_bottle", -- you can add a permission
    r=0,g=0,b=255, -- color
    max_units=10,
    units_per_minute=5,
    x=1390.90356445313,y=3604.98876953125,z=39.5187873840332, -- pos
    radius=5, height=1.5, -- area
    action="Make Meth", -- action name
    description="Cook up some crank! You can make meth by using 2 pills and 1 water bottle. You can sell this to people in SandyShores, or you can be a bit risky and drive up to grapeseed and get a little more cash!", -- action description
    in_money=0, -- money taken per unit
    out_money=0, -- money earned per unit
    reagents={
	  ["water"] = 1,
	  ["pills"] = 2}, -- items taken per unit
    products={ -- items given per unit
      ["meth"] = 1
    }
  }
}

return cfg
`
*Also I know I have 2 of the same fields jsut different transformer variants, otherwise it was doing this thing where even though i had the stock trans. set to the in game weedfield, it would set a gps out infront of SSPD... 0.o

**Comment by CruelAlpha** [comment] 2017-06-09 01:21
You arent ment to create many Transformers... its all just ment to be in one transformer, i encountered this.

**Comment by CruelAlpha** [comment] 2017-06-09 01:22
Only have one item transformer, and keep adding more columns into that one.

**Comment by ALongPantsMan** [comment] 2017-06-09 02:00
OH OH OHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH ty mate. someone just editing my code and I was like, well, what did i do wrong... he didnt speak english. lol. didnt see that at first

**Comment by jakepavek** [comment] 2017-06-09 02:05
What do you do? I was tryna figure it out

**Comment by TioSleepy** [comment] 2017-06-09 02:08
they are still temperamental, i have them all in one transformer and the work only under 12 players lol

**Comment by CruelAlpha** [comment] 2017-06-09 02:25
they all work
please close this issue, too there are too many uneeded topics open

**Comment by ImagicTheCat** [comment] 2017-06-09 03:02
Please read the issues guidelines... this is not a help section, and this is not a bug.

**Comment by ImagicTheCat** [comment] 2017-06-09 17:02
This issue it not compliant to the issues guidelines, please use the FiveM topic.

**Closed by ImagicTheCat** 2017-06-09 17:02 UTC
